using System;
using System.Collections.Generic;
using System.IO;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using SpawnThat.Configuration;
using SpawnThat.Core;
using SpawnThat.Utilities.Extensions;

namespace SpawnThat.Debugging.Datamining;

internal static class AltBiomesFileGenerator
{
    private const string FileName = "spawn_that.altbiomes.txt";

    public static void WriteToDiskAsToml()
    {
        try
        {
            if (ConfigurationManager.GeneralConfig?.WriteAltBiomesToFile.Value != true)
            {
                return;
            }

            using var stream = DebugFileWriter.PrepareFile(FileName, "datamined AltBiomes");

            stream.WriteLine($"# This file was auto-generated by Spawn That {SpawnThatPlugin.Version} at {DateTimeOffset.UtcNow.ToString("u")}, with Valheim '{Version.CurrentVersion.m_major}.{Version.CurrentVersion.m_minor}.{Version.CurrentVersion.m_patch}'.");
            stream.WriteLine($"# This file lists all alternative biomes (AltBiomes) loaded, with their internal settings.");
            stream.WriteLine($"# It is intended for debugging and datamining. Editting these will do nothing.");
            stream.WriteLine();

            for (int i = 0; i < AltBiomeList.m_altBiomes.Count; ++i)
            {
                stream.WriteLine($"[AltBiome.{i}]");

                if (AltBiomeList.m_altBiomes[i] is not null)
                {
                    WriteAltBiome(stream, AltBiomeList.m_altBiomes[i]);
                }
                stream.WriteLine();
                stream.Flush();
            }
        }
        catch (Exception e)
        {
            Log.LogWarning($"Error while trying to write {FileName}.", e);
        }
    }

    private static void WriteAltBiome(StreamWriter stream, AltBiome altBiome)
    {
        Write(x => x.m_name);
        Write(x => x.m_enabled);
        Write(x => x.m_biome);
        Write(x => x.m_namePrefix);
        Write(x => x.m_nameSuffix);
        Write(x => x.m_nameOverride);
        Write(x => x.m_levelUpChanceMultiplier);
        Write(x => x.m_forceMusic);
        Write(x => x.m_forceEnvironment);
        Write(x => x.m_addEnvironments);
        Write(x => x.m_blockEnvironments);
        Write(x => x.m_blockSpawnNames);
        Write(x => x.m_blockVegetationNames);
        Write(x => x.m_addLocations);
        Write(x => x.m_blockLocationNames);
        Write(x => x.m_baseHeightMultiplier);
        Write(x => x.m_baseHeightOffset);
        Write(x => x.m_heightMapMultiplier);
        Write(x => x.m_heightMapOffset);
        Write(x => x.m_heightMapBiomeOverride);
        Write(x => x.m_customGenerator);
        Write(x => x.m_minDistanceFromCenter);
        Write(x => x.m_minAmountSpawned);
        Write(x => x.m_maxAmountSpawned);
        Write(x => x.m_chance);
        Write(x => x.m_requireNeighbor);
        Write(x => x.m_notNeighbor);
        Write(x => x.m_incompatibleAltBiomes);
        Write(x => x.m_minEdgeSize);
        Write(x => x.m_maxEdgeSize);
        Write(x => x.m_minAvgHeight);
        Write(x => x.m_maxAvgHeight);
        Write(x => x.m_belowWorldX);
        Write(x => x.m_aboveWorldX);
        Write(x => x.m_belowWorldY);
        Write(x => x.m_aboveWorldY);
        Write(x => x.ValidPlacementSectors);
        Write(x => x.ValidPlacementSectorCombos);
        Write(x => x.m_spawn);

        void Write<K>(Expression<Func<AltBiome, K>> property, [CallerLineNumber] int sourceLineNumber = 0)
        {
            stream.Write(altBiome, property);
        }
    }
}

file static class AltBiomesWriterExtensions
{
    internal static void Write<K>(this StreamWriter writer, AltBiome biome, Expression<Func<AltBiome, K>> property)
    {
        var info = property.GetFieldInfo();

        var value = info.GetValue(biome);

        switch (value)
        {
            case null:
                writer.WriteLine($"{info.Name} = null");
                break;

            case List<EnvEntry> environments:
                writer.WriteContent(info, environments);
                break;

            case List<string> strings:
                writer.WriteContent(info, strings);
                break;

            case List<ZoneSystem.ZoneLocation> locations:
                writer.WriteContent(info, locations);
                break;

            case List<SpawnSystem.SpawnData> spawners:
                writer.WriteContent(info, spawners);
                break;

            default:
                writer.WriteLine($"{info.Name} = {value}");
                break;
        }
    }

    internal static void WriteContent(this StreamWriter writer, FieldInfo info, List<EnvEntry> environments)
    {
        writer.WriteLine($"{info.Name} = ");
        for (int i = 0; i < environments.Count; ++i)
        {
            if (environments[i] is null)
            {
                continue;
            }

            var index = string.Format("\t{0, -4}", $"[{i}]");
            var spacing = new string(' ', $"{index}: ".Length);

            writer.WriteLine(index + environments[i].PropString(x => x.m_environment));
            writer.WriteLine(spacing + environments[i].PropString(x => x.m_weight));
            writer.WriteLine(spacing + environments[i].PropString(x => x.m_ashlandsOverride));
            writer.WriteLine(spacing + environments[i].PropString(x => x.m_deepnorthOverride));
        }
    }

    internal static void WriteContent(this StreamWriter writer, FieldInfo info, List<string> strings)
    {
        writer.WriteLine($"{info.Name} = ");
        for (int i = 0; i < strings.Count; ++i)
        {
            if (strings[i] is null)
            {
                continue;
            }

            var index = string.Format("\t{0, -4}", $"[{i}]");
            var spacing = new string(' ', $"{index}: ".Length);

            writer.WriteLine(index + strings[i]);
        }
    }

    internal static void WriteContent(this StreamWriter writer, FieldInfo info, List<SpawnSystem.SpawnData> spawners)
    {
        writer.WriteLine($"{info.Name} = ");

        for (int i = 0; i < spawners.Count; ++i)
        {
            if (spawners[i] is null)
            {
                continue;
            }

            writer.WriteLine($"\t[{i}]");
            string indent = "\t\t";

            var spawn = spawners[i];

            var prefabName = spawn.m_prefab.GetCleanedName();

            writer.WriteLine(indent + spawn.PropString(x => x.m_name));
            writer.WriteLine(indent + spawn.PropString(x => x.m_enabled));
            writer.WriteLine(indent + $"m_prefab = {prefabName}");
            writer.WriteLine(indent + spawn.PropString(x => x.m_biome));
            writer.WriteLine(indent + spawn.PropString(x => x.m_biomeArea));
            writer.WriteLine(indent + spawn.PropString(x => x.m_maxSpawned));
            writer.WriteLine(indent + spawn.PropString(x => x.m_spawnInterval));
            writer.WriteLine(indent + spawn.PropString(x => x.m_spawnChance));
            writer.WriteLine(indent + spawn.PropString(x => x.m_spawnDistance));
            writer.WriteLine(indent + spawn.PropString(x => x.m_spawnRadiusMin));
            writer.WriteLine(indent + spawn.PropString(x => x.m_spawnRadiusMax));
            writer.WriteLine(indent + spawn.PropString(x => x.m_requiredGlobalKey));
            writer.WriteLine(indent + spawn.PropString(x => x.m_requiredEnvironments));
            writer.WriteLine(indent + spawn.PropString(x => x.m_requiredPersistentEvent));
            writer.WriteLine(indent + spawn.PropString(x => x.m_groupSizeMin));
            writer.WriteLine(indent + spawn.PropString(x => x.m_groupSizeMax));
            writer.WriteLine(indent + spawn.PropString(x => x.m_groupRadius));
            writer.WriteLine(indent + spawn.PropString(x => x.m_spawnAtNight));
            writer.WriteLine(indent + spawn.PropString(x => x.m_spawnAtDay));
            writer.WriteLine(indent + spawn.PropString(x => x.m_minAltitude));
            writer.WriteLine(indent + spawn.PropString(x => x.m_maxAltitude));
            writer.WriteLine(indent + spawn.PropString(x => x.m_minTilt));
            writer.WriteLine(indent + spawn.PropString(x => x.m_maxTilt));
            writer.WriteLine(indent + spawn.PropString(x => x.m_inForest));
            writer.WriteLine(indent + spawn.PropString(x => x.m_outsideForest));
            writer.WriteLine(indent + spawn.PropString(x => x.m_inLava));
            writer.WriteLine(indent + spawn.PropString(x => x.m_outsideLava));
            writer.WriteLine(indent + spawn.PropString(x => x.m_canSpawnCloseToPlayer));
            writer.WriteLine(indent + spawn.PropString(x => x.m_insidePlayerBase));
            writer.WriteLine(indent + spawn.PropString(x => x.m_minOceanDepth));
            writer.WriteLine(indent + spawn.PropString(x => x.m_maxOceanDepth));
            writer.WriteLine(indent + spawn.PropString(x => x.m_huntPlayer));
            writer.WriteLine(indent + spawn.PropString(x => x.m_groundOffset));
            writer.WriteLine(indent + spawn.PropString(x => x.m_groundOffsetRandom));
            writer.WriteLine(indent + spawn.PropString(x => x.m_minDistanceFromCenter));
            writer.WriteLine(indent + spawn.PropString(x => x.m_maxDistanceFromCenter));
            writer.WriteLine(indent + spawn.PropString(x => x.m_maxLevel));
            writer.WriteLine(indent + spawn.PropString(x => x.m_minLevel));
            writer.WriteLine(indent + spawn.PropString(x => x.m_levelUpMinCenterDistance));
            writer.WriteLine(indent + spawn.PropString(x => x.m_overrideLevelupChance));
        }
    }

    internal static void WriteContent(this StreamWriter writer, FieldInfo info, List<ZoneSystem.ZoneLocation> locations)
    {
        writer.WriteLine($"{info.Name} = ");
        for (int i = 0; i < locations.Count; ++i)
        {
            if (locations[i] is null)
            {
                continue;
            }

            var index = string.Format("\t{0, -4}", $"[{i}]");
            var spacing = new string(' ', $"{index}: ".Length);

            writer.WriteLine(index + locations[i].PropString(x => x.m_name));
        }
    }

    internal static string PropString<T, K>(this T obj, Expression<Func<T, K>> property)
    {
        var prop = property.GetFieldInfo();

        var value = prop.GetValue(obj);

        if (value is List<string> strings)
        {
            return $"{prop.Name} = {string.Join(", ", strings)}";
        }
        else
        {
            return $"{prop.Name} = {value}";
        }        
    }

    internal static FieldInfo GetFieldInfo<T, K>(this Expression<Func<T, K>> propertySelector)
    {
        var memberExpression = propertySelector.Body as MemberExpression;

        var property = memberExpression?.Member as FieldInfo;

        return property;
    }
}